In [6]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import glob
import os
import sys

# Select file to preview
file = 'Listings'
path = f'../raw/{file}.csv'
df = pd.read_csv(path, low_memory=False)
df.head(15)

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,...,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,281420,"Beautiful Flat in le Village Montmartre, Paris",1466919,12/3/2011,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
1,3705183,39 mÂ² Paris (Sacre CÅ“ur),10328771,11/29/2013,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
2,4082273,"Lovely apartment with Terrace, 60m2",19252768,7/31/2014,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
3,4797344,Cosy studio (close to Eiffel tower),10668311,12/17/2013,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
4,4823489,Close to Eiffel Tower - Beautiful flat : 2 rooms,24837558,12/14/2014,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
5,4898654,NEW - Charming apartment Le Marais,505535,4/13/2011,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
6,6021700,2P - Entre Bastille et Republique,8053690,8/9/2013,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
7,6945740,57sqm btw. Bastille & PÃ¨re Lachaise,5924709,4/14/2013,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
8,7491966,Charming appartment near the Parc Buttes Chaumont,35812762,6/14/2015,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
9,7849932,Bel appartement plein de charme !,20833291,9/2/2014,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
10,7995091,Beau 2piÃ¨ces prÃ¨s Butte aux cailles,35014275,6/4/2015,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
11,9011901,Cosy appartement in marais 40m2,19939276,8/13/2014,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
12,9880847,Cosy Flat near Rue Mouffetard,18264466,7/17/2014,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
13,9898855,Grand 2 piÃ¨ces de 60 m2 cosy au canal Saint M...,10121410,11/19/2013,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
14,10266213,"Studio pour deux, place de clichy",52785202,12/30/2015,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f

In [10]:
# Filter by location
narrowdf = df.loc[(df["host_location"] == 'New York, New York, United States')]
narrowdf.head()

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,...,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
11615,657198,"2BR gem in Cobble Hill, Brooklyn",414627,2/28/2011,"New York, New York, United States",NaN,NaN,0.0,f,1.0,...,3,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
11616,786685,Big brownstone garden apt w patio on great block,4147380,11/14/2012,"New York, New York, United States",NaN,NaN,0.9,t,1.0,...,4,1125,97.0,10.0,10.0,10.0,10.0,10.0,9.0,f
11617,849567,Your own large 1BR apt in Manhattan,52394,11/8/2009,"New York, New York, United States",NaN,NaN,0.5,f,1.0,...,88,1125,99.0,10.0,9.0,10.0,10.0,9.0,10.0,f
11618,1268175,Cozy and full of plants,6903071,6/13/2013,"New York, New York, United States",NaN,NaN,0.8,t,1.0,...,2,1125,96.0,10.0,10.0,10.0,10.0,9.0,9.0,f
11619,1567225,"NYC LARGE 3 BR West Side Manhattan, New York City",8336526,8/22/2013,"New York, New York, United States",NaN,NaN,0.0,f,1.0,...,5,1125,95.0,10.0,10.0,10.0,10.0,10.0,9.0,f

In [11]:
len(narrowdf)

24040